# Generated by Django 4.0.2 on 2022-04-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Tabela',
            },
        ),
        migrations.CreateModel(
            name='Rotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(verbose_name='Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('pago', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pago')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('id_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preco', verbose_name='Preço')),
                ('id_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name_plural': 'Rotativos',
            },
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_vencimento', models.IntegerField(default=5, verbose_name='Dia de vencimento')),
                ('pendencia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pendência')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('id_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preco', verbose_name='Preço')),
            ],
            options={
                'verbose_name_plural': 'Mensalista',
            },
        ),
    ]
