# Generated by Django 4.0.2 on 2022-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preco_rotativo_mensalista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Forma de pagamento')),
            ],
            options={
                'verbose_name_plural': 'Forma de pagamento',
            },
        ),
        migrations.AlterModelOptions(
            name='rotativo',
            options={'verbose_name_plural': 'Rotativo'},
        ),
        migrations.AddField(
            model_name='mensalista',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor com desconto'),
        ),
    ]
