# Generated by Django 4.0.2 on 2022-05-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forma_pagamento_alter_rotativo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.forma_pagamento', verbose_name='Forma de pagamento'),
        ),
    ]
