# Generated by Django 4.0.2 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensalista_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='pendencia',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Pendência'),
        ),
    ]
